# WIZ5XXSR-RP-C_BUILD_DEFINE: WIZ5XXSR-RP-C_SDK_VERSION_MAJOR, SDK major version number
set(WIZ5XXSR-RP-C_SDK_VERSION_MAJOR 1)
# WIZ5XXSR-RP-C_BUILD_DEFINE: WIZ5XXSR-RP-C_SDK_VERSION_MINOR, SDK minor version number
set(WIZ5XXSR-RP-C_SDK_VERSION_MINOR 0)
# WIZ5XXSR-RP-C_BUILD_DEFINE: WIZ5XXSR-RP-C_SDK_VERSION_REVISION, SDK version revision
set(WIZ5XXSR-RP-C_SDK_VERSION_REVISION 7)
# WIZ5XXSR-RP-C_BUILD_DEFINE: WIZ5XXSR-RP-C_SDK_VERSION_STRING, SDK version
set(WIZ5XXSR-RP-C_SDK_VERSION_STRING "${WIZ5XXSR-RP-C_SDK_VERSION_MAJOR}.${WIZ5XXSR-RP-C_SDK_VERSION_MINOR}.${WIZ5XXSR-RP-C_SDK_VERSION_REVISION}")

message(STATUS "WIZ5XXSR-RP-C SDK version is ${WIZ5XXSR-RP-C_SDK_VERSION_STRING}")
